### ISSUE TITLE
Exhaustion and Rest will not expand when mousing over in Firefox

### ISSUE THREAD

**Issue by hellb0rg** [kgar/foundry-vtt-tidy-5e-sheets#42]
The feature works as expected when running Edge (and i assume Chrome works as they are both chromium based) but when running FoundryVTT through Firefox the fields do not expand.

My browser string:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0

**Comment by hellb0rg** [comment]
This is due to Mozilla not having the :has() pseudo-selector active by default. Users can get around this by enabling this selector which a quick google can tell one how to do.

Should be fixed when Firefox 120 is released, which is later this month (tentative release date 21th of November 2023).

**Comment by kgar** [comment]
I updated to 120 this morning, but it looks like `:has()` is still not enabled by default. They moved it to the 121 release: https://www.mozilla.org/en-US/firefox/121.0a1/releasenotes/ that is scheduled for Dec 19. 😞

**Comment by kgar** [comment]
I updated to 121, and I see now that `layout.css.has-selector` defaults to `true`. This could mean it's finally compatible by default. Can you confirm or deny from your side?

**Comment by kgar** [comment]
Users are reporting that the issue is now resolved when updating Firefox. Closing issue 🎉
