### ISSUE TITLE
Show Players a Token image by Right Clicking on NPC portrait and "Show Token" broken when is the Token is using wildcards in path.

### ISSUE THREAD

**Issue by BillPitcher** [kgar/foundry-vtt-tidy-5e-sheets#638]
When want to show the players a large version of the Token I often use the Right click on the NPC character sheet to show the token image. This works great for NPC's with a normal path, but is the Token is using  wildcard tokens it try to load the path with the * in it and fails. It needs to use the path to the current token.

At the moment to workaround I copy and paste the token path into a journal and show it from there, but it's a bit clunky for on the fly play.

cheers
Bill

**Comment by kgar** [comment]
Thanks for reporting. Can you show me an example that I might recreate the issue? 

I'm having trouble trying to recreate. I can't save a file with any wildcards in it, and I can't get images to show up when there's a wildcard in the path.

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/31139cf8-9468-456e-bfe8-18bb8a0908ca)

![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/b74e6d13-d381-4e13-9fce-a328b822890f)

Some more questions to help me figure it out:
Which operating system is Foundry running on?
What Foundry, dnd5e, and Tidy versions are in use?
Are images with wildcards in their path working in general when selecting a token image on the default sheets or the legacy sheets?

**Comment by BillPitcher** [comment]
<img width="699" alt="Screenshot 2024-06-08 at 1 52 36 PM" src="https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4987108/bb646147-cfd2-4d8c-8ed8-d2e3e6819685">
This is an example, in the Token Prototype I have wildcard set
<img width="555" alt="Screenshot 2024-06-08 at 1 53 21 PM" src="https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4987108/97d62498-5a42-4fdf-8e04-8c0667aaf2e4">
And they are from the list of Tokens
<img width="570" alt="Screenshot 2024-06-08 at 1 53 55 PM" src="https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4987108/d36f4da6-117c-4944-a55f-66c9a28d416c">
When I select Show Token by Right Clicking on the Portrait Image
<img width="334" alt="Screenshot 2024-06-08 at 1 54 16 PM" src="https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4987108/8a3431ab-db5c-43d2-8d6d-33021c0ea754">


<img width="633" alt="Screenshot 2024-06-08 at 1 54 40 PM" src="https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4987108/036854c6-26f0-4fdc-8d96-6fd07ce70660">
I get... And in the Console

<img width="698" alt="Screenshot 2024-06-08 at 1 55 16 PM" src="https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4987108/f00a03b1-7cd8-4a2a-88ad-efb2322449ff">

It shows it's trying to fetch the filename with the "*" wildcard in it

**Comment by kgar** [comment]
Ah! My apologies. This is a feature I never knew about until now. I'll learn how it works and see what I can do. Thank you again for helping me with this info.

**Comment by kgar** [comment]
Tidy V4.2.0 has the fix.

Thank you again for reporting this. I learned about wildcards, and this exposed a related bug that is now fixed, so every Tidy user has benefitted from your efforts.

**Comment by BillPitcher** [comment]
I've been testing this and we still have a little problem, if the Ring is set to true, it shows the non-ring Token. I'm not sure if there is a good solution to this. I suppose if the ring is true you could show the -subject img.

We don't get a broken img link dow so, great work!!!

**Comment by kgar** [comment]
Glad to be able to help!

If it's having trouble showing the token ring on the canvas, this may be a Foundry / dnd5e issue.

For the image preview feature, I don't think I can visualize the dynamic token ring from the preview window in a standard way. Are there examples of this in the system? I may be able to look at how they're doing it.

**Comment by kgar** [comment]
I will leave it to dnd5e / Foundry to deal with the management of the dynamic token ring. I think it would add too much additional complexity to Tidy to try to work that out in the image preview window.

Thanks again for reporting the wildcard issue. Come back anytime!
